# Generated by Django 3.2.5 on 2021-07-25 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zisanhukuk', '0002_auto_20210725_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('kategori', multiselectfield.db.fields.MultiSelectField(choices=[('Boya Badana', 'Boya Badana'), ('Elektrik', 'Elektrik'), ('Cati', 'Cati'), ('Demir Ferforje', 'Demir Ferforje'), ('Kapi Pencere', 'Kapi Pencere'), ('Zemin Kaplama', 'Zemin Kaplama')], max_length=1000, null=True)),
                ('website', models.CharField(default='ananas.website', max_length=200, null=True)),
                ('eposta', models.CharField(max_length=200, null=True)),
                ('telefon', models.CharField(max_length=200, null=True)),
                ('resim', models.ImageField(default='ananas.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
