# Generated by Django 3.2.5 on 2021-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0003_haber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haber',
            name='eposta',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='website',
        ),
        migrations.AddField(
            model_name='haber',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
