# Generated by Django 3.2.5 on 2021-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0004_auto_20210726_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='aciklama',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
