# Generated by Django 3.2.5 on 2021-07-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0005_haber_aciklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haber',
            name='user',
        ),
    ]
