# Generated by Django 3.2.5 on 2021-07-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0006_remove_haber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
    ]
