# Generated by Django 3.2.5 on 2021-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0008_auto_20210726_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
