# Generated by Django 3.2.5 on 2021-07-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0012_alter_haber_dosya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='resim',
            field=models.ImageField(default='faqs.jpg', upload_to='profile_images'),
        ),
    ]
