# Generated by Django 3.2.5 on 2021-07-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0015_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
