# Generated by Django 3.2.5 on 2021-07-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zisanhukuk', '0017_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='kategori',
        ),
    ]
